<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace SwaggerClient\models;

use \ArrayAccess;

class OutputFile implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'string',
      'source' => 'object',
      'uri' => 'string',
      'filename' => 'string',
      'size' => 'int',
      'created_at' => 'DateTime'
  );

  static $attributeMap = array(
      'id' => 'id',
      'source' => 'source',
      'uri' => 'uri',
      'filename' => 'filename',
      'size' => 'size',
      'created_at' => 'created_at'
  );

  
  /**
  * Unique identifier for the file.
  */
  public $id; /* string */
  /**
  * Sources for the files including the input files and conversion used.
  */
  public $source; /* object */
  /**
  * Url for downloading the file.
  */
  public $uri; /* string */
  /**
  * Filename of the file.
  */
  public $filename; /* string */
  /**
  * Size of the file in bytes.
  */
  public $size; /* int */
  /**
  * Date and time when the job was created.
  */
  public $created_at; /* DateTime */

  public function __construct(array $data = null) {
    $this->id = $data["id"];
    $this->source = $data["source"];
    $this->uri = $data["uri"];
    $this->filename = $data["filename"];
    $this->size = $data["size"];
    $this->created_at = $data["created_at"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
