name: Tests

on:
    pull_request:
        branches:
            - master

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-versions: ["8.3", "8.2", "8.1", "8.0", "7.4", "7.3", "7.2", "7.1"]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      dependencies-php-${{ matrix.php-versions }}-composer-
                      dependencies-php-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: json, dom, curl, libxml, mbstring
                  coverage: none

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Execute tests
              run: bin/phpunit --testsuite unit
              env:
                  OC_API_KEY: ${{ secrets.OC_API_KEY }}
